# -*- coding: utf-8 -*-
"""testing hypothesis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pw9xqyjndbONk4GS0jsTUXQKN6R8ZP_3
"""

pd.crosstab(df['most ads day'], df['converted'], normalize='index')

sns.kdeplot(control['total ads'], label='Control')
sns.kdeplot(test['total ads'], label='Test')
plt.legend()
plt.title("Total Ads Exposure Distribution")
plt.show()

rates = pd.DataFrame({
    'test group': ['control', 'test'],
    'conversion_rate': [control_rate, test_rate]
})

sns.barplot(x='test group', y='conversion_rate', data=rates)
plt.title("Conversion Rate by Test Group")
plt.show()

if n_test == 0 or n_control == 0:
    raise ValueError("One of the groups has zero samples. Check group labels.")

diff = test_rate - control_rate

n_test = len(test)
n_control = len(control)

se = np.sqrt(
    (test_rate * (1 - test_rate) / n_test) +
    (control_rate * (1 - control_rate) / n_control)
)

ci_low = diff - 1.96 * se
ci_high = diff + 1.96 * se

(ci_low, ci_high)

control_rate = control['converted'].mean()
test_rate = test['converted'].mean()

control_rate, test_rate

len(control), len(test)

control = df[df['test group'] == 'psa']   # control
test = df[df['test group'] == 'ad']       # treatment

df['test group'].unique()

n_control = len(control)
n_test = len(test)

n_control, n_test

if p_value < alpha:
    print("Reject H0: Statistically significant difference in conversion")
else:
    print("Fail to reject H0: No statistically significant difference")

chi2, p_value, dof, expected = stats.chi2_contingency(contingency)
p_value

contingency = pd.crosstab(df['test group'], df['converted'])
contingency

control_rate = control['converted'].mean()
test_rate = test['converted'].mean()

control_rate, test_rate

alpha = 0.05

control = df[df['test group'] == 'control']
test = df[df['test group'] == 'test']

df['test group'].value_counts()

df.head()

# Clean column names
df.columns = df.columns.str.strip()

# Drop useless index column
df = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv("marketing_AB.csv")

import pandas as pd
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
import seaborn as sns